### ISSUE TITLE
EC2 Driver Playbooks infer too much.

### ISSUE THREAD

**Issue by nbering** [metacloud/molecule#955] opened 2017-09-18 13:47 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.3.1.0 (detached HEAD 5a3f52d988) last updated 2017/05/11 16:12:45 (GMT -400)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

molecule --version
molecule, version 2.0.4
```

- Molecule installation method: pip
- Ansible installation method: source

# Desired Behaviour

- EC2 Driver allow override of the OS username.
- EC2 Driver should allow users to specify a region that matches the machine image selection.

# Actual Behaviour (Bug report only)

- Username is hard-coded to 'ubuntu', which is inappropriate for any distro except Ubuntu.
- Region is not specified at all, relying on Environment variables or other methods to determine region.

# Proposal

I can put together a pull request to clean up some of the cases whether the driver's author made some assumptions. I'm just putting the feelers out first as to whether there would be any interest in taking my contribution.

**Comment by retr0h** [comment] 2017-09-19 19:38
The drivers are used mostly as reference, especially when it comes to GCE, EC2, and Openstack, since deployments very, and are fairly customized.  The developer is free to customize the molecule and create/destroy files as they choose.

Basically, this is by design.  One deployment doesn't fit all.

**Comment by nbering** [comment] 2017-09-19 23:14
Thanks. I'll look into making a Pull Request, then. Thank your for responding.

**Comment by retr0h** [comment] 2017-10-06 22:23
I'm going to close this issue as it is not something I am planning to fix.  The `molecule.yml` file isn't generally intended to be all encompassing.  If one wishes to clean it up and submit a PR I'm good with that.

**Closed by retr0h** 2017-10-06 22:23 UTC

**Comment by nbering** [comment] 2017-10-07 13:02
That's ok, don't leave the issue open on my account. I'm hoping to get a PR together at some point, but have been pretty busy. Thanks for looking at it.
