### ISSUE TITLE
docker-py package breaks using docker-compose

### ISSUE THREAD

**Issue by timja-kainos** [metacloud/molecule#743] opened 2017-02-06 16:04 UTC
# Issue Type

- Bug report

# Molecule and Ansible details
- Molecule installation method: One of source, pip
pip
- Ansible installation method: One of source, pip, OS package
os package
# Desired Behaviour
I can use docker-compose and molecule on the same machine

# Actual Behaviour (Bug report only)
Installing `docker-py` conflicts with the new package `docker`

```
Traceback (most recent call last):
  File "/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 20, in <module>
    from ..bundle import get_image_digests
  File "/usr/lib/python2.7/site-packages/compose/bundle.py", line 13, in <module>
    from .network import get_network_defs_for_service
  File "/usr/lib/python2.7/site-packages/compose/network.py", line 7, in <module>
    from docker.types import IPAMConfig
ImportError: cannot import name IPAMConfig
```

See:
https://github.com/docker/compose/issues/4401
https://github.com/docker/docker-py/issues/1431

`docker-py` appears to be obsoleted and `docker` is the new pip package

**Comment by abtreece** [comment] 2017-02-07 04:52
Docker changed the name of the Docker Python SDK to just `docker` when they bumped to version 2. The last docker-py version is 1.10.6.  Molecule is only capable of using docker-py due to changes that have been to the API in v2. AFAIK we won't be supporting the v2 docker b/c molecule is going to transition to using the Ansible implementation of Docker.

As you've discovered you can't have both `docker-py` and `docker` installed which is by design by Docker.

**Comment by abtreece** [comment] 2017-02-07 16:00
Thinking about this more... in order to use docker-compose and molecule together you will likely need to install docker-compose via a method other than `pip`. On a Mac or Windows machine docker-compose comes with the installation of Docker Engine. You can also pull down the docker-compose binary by itself via a curl command documented here... https://docs.docker.com/compose/install/

**Comment by retr0h** [comment] 2017-02-07 16:36
> AFAIK we won't be supporting the v2 docker b/c molecule is going to transition to using the Ansible implementation of Docker.

Also, these `docker_` modules require `docker-py`, so I probably wont be spending effort porting Molecule to the `docker` pip package.

**Comment by retr0h** [comment] 2017-02-07 16:37
> Thinking about this more... in order to use docker-compose and molecule together you will likely need to install docker-compose via a method other than pip. On a Mac or Windows machine docker-compose comes with the installation of Docker Engine. You can also pull down the docker-compose binary by itself via a curl command documented here... https://docs.docker.com/compose/install/

Good point as well.  I can run Molecule and the entire docker toolchain, since I have installed docker using the Docker installer.  Not through pip.

**Comment by retr0h** [comment] 2017-02-08 21:56
Won't be moving to `docker` anytime soon.  See workarounds above.

**Closed by retr0h** 2017-02-08 21:56 UTC
Labels: question

**Comment by timja-kainos** [comment] 2017-02-13 09:17
In case anyone is interested ansible devel branch supports both `docker-py` and `docker`
Here is the commit that introduced support:
https://github.com/ansible/ansible/commit/e2a1ce2916e9b87fe1ad4a1011c04ef8d2faf046

**Comment by timja-kainos** [comment] 2017-03-08 12:08
@abtreece @retr0h The workaround of installing the compose binary from somewhere other than `pip` no longer works.

docker-compose has added a check to see if `docker-py` exists and fails fast with:
```
ERROR: Dependency conflict: an older version of the 'docker-py' package is polluting the namespace. Run the following command to remedy the issue:
pip uninstall docker docker-py; pip install docker
```

Is there another workaround?

**Comment by retr0h** [comment] 2017-03-08 19:42
> Is there another workaround?

Run molecule in a virtualenv?  Since the bug report is about running docker-compose and molecule on the same system, you simply need to run molecule in a venv.

**Comment by retr0h** [comment] 2017-03-09 01:10
@kireledan Would you be interested in porting Molecule to the new docker package vs docker-py?

**Comment by kireledan** [comment] 2017-03-10 17:15
Sure. I'll take a look
