### ISSUE TITLE
Molecule performance

### ISSUE THREAD

**Issue by mejo-** [metacloud/molecule#1056] opened 2017-12-03 15:26 UTC
Hi,

I recently discovered Geerlingguys test suite for Ansible (see e.g. [here for his role `ansible-role-apache`](https://github.com/geerlingguy/ansible-role-apache/blob/master/.travis.yml) and gave it a try. I was surprised that it runs up to ten times faster (on Travis CI) than comparable molecule tests.

After discussing the issue in #molecule-users on IRC, I did some further investigation. I did all comparison tests with my [`ansible-role-mariadb`](https://github.com/mejo-/ansible-role-mariadb). Testing the role on two platforms (Debian Jessie and Debian Stretch) using Python2.7 and Ansible 2.4 took [9 minutes using tox+molecule](https://travis-ci.org/mejo-/ansible-role-mariadb/builds/310810536) (branch [`molecule-test`](https://github.com/mejo-/ansible-role-mariadb/tree/molecule-test)) while it took [only 3.5 minutes using Geerlingguys testsuite](https://travis-ci.org/mejo-/ansible-role-mariadb/builds/310434134) (branch [`new-test-setup`](https://github.com/mejo-/ansible-role-mariadb/tree/new-test-setup)). That's a ratio of 2.5:1.

Here's my findings so far:

First I thought the reason is that molecule creates the docker image from a `Dockerfile` while the solution by Geerlingguy [directly uses his Docker images](https://gist.github.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/#file-ansible-role-test-sh-L66). But [according to Travis CI](https://travis-ci.org/mejo-/ansible-role-mariadb/builds/310810536#L633), this only takes 46 seconds). So it doesn't explain the big gap.

Then I enabled the [Ansible plugin `profile_tasks`](https://docs.ansible.com/ansible/devel/plugins/callback/profile_tasks.html) to compare the actual task run times.

Surprisingly, it turned out that the tasks run much faster when using geerlingguys test suite: the task `install mariadb client+server` takes [261 seconds]](https://travis-ci.org/mejo-/ansible-role-mariadb/builds/310810536#L633) with molecule on two platforms. With geerlingguys test suite on one platform, the same task needs [only 63 seconds](https://travis-ci.org/mejo-/ansible-role-mariadb/jobs/310818315#L540). This means a ratio of 4:1 while it should only be 2:1 (molecule runs the task on two platforms while geerlingguys solution starts two separate runs and the log shows only one).

Both solutions use the same Docker images. See [the molecule setup](https://github.com/mejo-/ansible-role-mariadb/blob/molecule-test/molecule/default/molecule.yml#L11) vs. [the setup copied from geerlingguy](https://gist.github.com/mejo-/06855312913ea0ffd834ffe0270d154c#file-ansible-role-test-sh-L70).

To be honest I'm a bit clueless how to further investigate. What could be the reason for this dramatic difference in speed? A speed improvement of 4:1 or even more is a very good reason to switch away from molecule. Still I very much prefer the configurable and well-documented approach of molecule. So the best would be to find the cause and improve molecule's speed :)

**Comment by retr0h** [comment] 2017-12-03 22:40
> Surprisingly, it turned out that the tasks run much faster when using geerlingguys test suite: the task install mariadb client+server takes [261 seconds]](https://travis-ci.org/mejo-/ansible-role-mariadb/builds/310810536#L633) with molecule on two platforms. With geerlingguys test suite on one platform, the same task needs only 63 seconds. This means a ratio of 4:1 while it should only be 2:1 (molecule runs the task on two platforms while geerlingguys solution starts two separate runs and the log shows only one).

Without digging too deep, I believe the issue is related to the way [Geerlingguy's solution](https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/) [performs a converge](https://travis-ci.org/mejo-/ansible-role-mariadb/jobs/310818315#L500).  It is performing the converge locally inside the container (similar to `kitchen-ansible`) vs Molecule's ansible-connection=`docker`.

**Comment by retr0h** [comment] 2017-12-05 05:38
We also landed some docs on using [detox](http://molecule.readthedocs.io/en/latest/testing.html#detox), which may help in some cases.

**Comment by retr0h** [comment] 2017-12-20 23:49
Closing this out as there isn't much we can do about this at the moment.  Running a container locally will always be faster.

**Closed by retr0h** 2017-12-20 23:49 UTC
