### ISSUE TITLE
--debug mode not documented in --help output

### ISSUE THREAD

**Issue by MarkusTeufelberger** [metacloud/molecule#1020] opened 2017-10-30 13:37 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.1.0
molecule 2.3.1
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

`--debug` should be documented when running `molecule [command] --help`

# Actual Behaviour (Bug report only)

````
molecule test --help
Usage: molecule test [OPTIONS]

  Test (destroy, create, converge, lint, verify, destroy).

Options:
  -s, --scenario-name TEXT        Name of the scenario to target. (default)
  -d, --driver-name [delegated|docker|ec2|gce|lxc|lxd|openstack|vagrant]
                                  Name of driver to use. (docker)
  --all / --no-all                Test all scenarios. Default is False.
  --destroy [always|never]        The destroy strategy used at the conclusion
                                  of a Molecule run (never).
  --help                          Show this message and exit.
````

**Comment by retr0h** [comment] 2017-10-30 16:48
The `--debug` flag is documented under `molecule --help` only displays the flags which are available to the subcommand.  Debug is not a subcommand flag.

**Comment by MarkusTeufelberger** [comment] 2017-10-30 17:42
Thanks, makes sense. It would still be nice if it could be changed, feel free to close as `wontfix` in case you don't want to.

**Comment by retr0h** [comment] 2017-10-30 20:59
@MarkusTeufelberger I would need to see how [click](http://click.pocoo.org/5/) handles this.  I am not entirely sure if this is by design or a flaw.

**Comment by retr0h** [comment] 2017-10-30 22:04
Thanks for the report @MarkusTeufelberger.  Closing out since this is the way click behaves.

**Closed by retr0h** 2017-10-30 22:04 UTC
