### ISSUE TITLE
Molecule login crash on iTerm2 resize window

### ISSUE THREAD

**Issue by chrisb3ll** [metacloud/molecule#545] opened 2016-10-07 20:44 UTC
When using `moelcule login` to ssh into a test instance, any action to resize the shell window in iTerm2 results in the error below and exits the test instance.

Not a big deal, just a minor inconvenience. 
Please let me know if there is anything I can do to help.

```
vagrant@test-logstash1:~$ Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 68, in main
    CLI().main()
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 64, in main
    util.sysexit(c.execute()[0])
  File "/usr/local/lib/python2.7/site-packages/molecule/command/login.py", line 114, in execute
    self.molecule._pt.interact()
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 745, in interact
    self.__interact_copy(escape_character, input_filter, output_filter)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 770, in __interact_copy
    r, w, e = select_ignore_interrupts([self.child_fd, self.STDIN_FILENO], [], [])
  File "/usr/local/lib/python2.7/site-packages/pexpect/utils.py", line 138, in select_ignore_interrupts
    return select.select(iwtd, owtd, ewtd, timeout)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/login.py", line 124, in _sigwinch_passthrough
    self._pt.setwinsize(a[0], a[1])
AttributeError: 'Login' object has no attribute '_pt'
```

**Comment by lxhunter** [comment] 2016-10-07 21:35
+1

**Comment by retr0h** [comment] 2016-10-08 03:22
I know this is an issue, @abrown-sg brought this up a while back.  However, I cannot duplicate it.  Can you tell me what to do?  I have fired up an instance, logged in via `molecule login` and am resizing my iterm2 window.

**Comment by lxhunter** [comment] 2016-10-08 06:38
I will make a Video

**Comment by retr0h** [comment] 2016-10-08 07:28
Sweet 👌

**Comment by lxhunter** [comment] 2016-10-08 08:05
hey retr0h,

here it is: https://dl.dropboxusercontent.com/u/16675326/molecule_crash.mov

If you need to know more about my shell: https://github.com/lxhunter/dotfiles

otherwise shout ;)

Thanks!

**Comment by retr0h** [comment] 2016-10-08 22:48
hi @lxhunter the video doesn't really show how you resized the window.  Do you type a key combo?  When I drag the window with my mouse, I cannot reproduce.  Any additional info you have would be helpful.

**Comment by lxhunter** [comment] 2016-10-08 23:16
Hey John, 

the "pill" on the lower right side lights up a little as I drag with the mouse. I can redo it tomorrow. I use iTerm 2 if that help.

Will look for further info.

Cheers

**Comment by chrisb3ll** [comment] 2016-10-09 20:46
Hi @retr0h - apologies, I just upgraded to 1.12.4 (from 1.11.4) and its fixed.

**Comment by retr0h** [comment] 2016-10-09 21:39
@chrisb3ll @lxhunter Looks like this was fixed inadvertently during a coverage test [PR](https://github.com/metacloud/molecule/commit/660edb7ce96737ac228bd6c29a40b209c9588a56#diff-ebeba8a0da2dabde2e254879dbb02a87L105).

**Comment by retr0h** [comment] 2016-10-10 18:46
@lxhunter can you confirm against 1.12 series?

**Comment by lxhunter** [comment] 2016-10-10 21:58
confirmed! Thanks!!!

**Closed** 2016-10-10 22:39 UTC
Labels: question
