### ISSUE TITLE
Passing CLI flags to --test seems to be broken

### ISSUE THREAD

**Issue by abrown-sg** [metacloud/molecule#281] opened 2016-07-25 20:57 UTC
Here's an example from current master in demo/molecule:

```
$ molecule test --platform centos7
--> Destroying instances ...
--> Checking playbooks syntax ...

playbook: playbook.yml

--> Creating instances ...
Bringing machine 'demo-01' up with 'virtualbox' provider...
==> demo-01: Importing base box '**ubuntu/trusty64**'...
```

**Comment by retr0h** [comment] 2016-07-25 21:14
Looks like a dupe of https://github.com/metacloud/molecule/issues/199.

**Comment by retr0h** [comment] 2016-07-25 21:20
Closing as dupe.

**Closed by retr0h** 2016-07-25 21:20 UTC
