### ISSUE TITLE
Wait for instance(s) deletion to complete

### ISSUE THREAD

**Issue by bbaassssiiee** [metacloud/molecule#1384] opened 2018-07-13 11:12 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/Users/bas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

```
molecule, version 2.16.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

pip install molecule

# Desired Behavior
A run with nor errors
```
molecule init role --role-name bugreport
cd bugreport/
molecule test
```

# Actual Behaviour (Bug report only)

```
demo:bugreport bas$ molecule test
--> Validating schema /Users/bas/code/dockpack/molecule2/bugreport/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix

└── default
    ├── lint
    ├── destroy
    ├── dependency
    ├── syntax
    ├── create
    ├── prepare
    ├── converge
    ├── idempotence
    ├── side_effect
    ├── verify
    └── destroy

--> Scenario: 'default'
--> Action: 'lint'
--> Executing Yamllint on files found in /Users/bas/code/dockpack/molecule2/bugreport/...
Lint completed successfully.
--> Executing Flake8 on files found in /Users/bas/code/dockpack/molecule2/bugreport/molecule/default/tests/...
Lint completed successfully.
--> Executing Ansible Lint on /Users/bas/code/dockpack/molecule2/bugreport/molecule/default/playbook.yml...
Lint completed successfully.
--> Scenario: 'default'
--> Action: 'destroy'

    PLAY [Destroy] *****************************************************************

    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=None)
    changed: [localhost]

    TASK [Wait for instance(s) deletion to complete] *******************************
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

    PLAY RECAP *********************************************************************
    localhost                  : ok=1    changed=1    unreachable=0    failed=1


ERROR:
An error occurred during the test sequence action: 'destroy'. Cleaning up.
--> Scenario: 'default'
--> Action: 'destroy'

    PLAY [Destroy] *****************************************************************

    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=None)
    changed: [localhost]

    TASK [Wait for instance(s) deletion to complete] *******************************
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

    PLAY RECAP *********************************************************************
    localhost                  : ok=1    changed=1    unreachable=0    failed=1


ERROR
```

**Comment by bbaassssiiee** [comment] 2018-07-13 11:12
Python 2.7.15

**Comment by retr0h** [comment] 2018-07-14 00:37
Have a link to the role in question?

**Comment by retr0h** [comment] 2018-07-14 15:55
> It is a new (empty) role. Molecule is the only pip module installed, with ansible as dependency. So therefore it is as default as it gets.

Thats the first problem.  You need to pip install `docker` also.  Have a look at the README.

**Comment by retr0h** [comment] 2018-07-15 01:05
@infothrill I cannot reproduce.  Ansible 2.6 *must* use *docker* not *docker-py*.  I was able to execute your role and receive linting errors, since the role isn't setup to use the .yamllint file.

```
[jodewey:/tmp/molecule-bugreport] [molecule-bugreport] master* 1 ± pip freeze | egrep "(molecule|ansible|docker)"
ansible==2.6.1
ansible-lint==3.4.23
docker==3.4.1
docker-pycreds==0.3.0
molecule==2.16.0
```

Try running molecule with `--debug` the nolog output isn't useful.

**Comment by bbaassssiiee** [comment] 2018-07-15 10:06
The behaviour described by @infothrill occured to me too, but not in all roles. Dunno why.

**Comment by infothrill** [comment] 2018-07-15 13:49
I updated the information at https://github.com/infothrill/molecule-bugreport

# Molecule docker error with ansible 2.6+

Example role to investigate and re-produce the behaviour described in https://github.com/metacloud/molecule/issues/1384

# Molecule and Ansible details

```
molecule --version
molecule, version 2.16.0
```

```
ansible --version
ansible 2.6.1
  config file = None
  configured module search path = [u'/Users/infothrill/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/infothrill/tmp/molecule-bugreport/.tox/ansible26/lib/python2.7/site-packages/ansible
  executable location = /Users/infothrill/tmp/molecule-bugreport/.tox/ansible26/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

docker, docker-machine

```
Docker version 18.05.0-ce, build f150324
docker-machine version 0.15.0, build b48dc28
```

tox version

```
tox --version
3.1.2 imported from /Users/infothrill/.local/venvs/tox/lib/python3.6/site-packages/tox/__init__.py
```

tox pip information:

```
ansible26 create: /Users/infothrill/tmp/molecule-bugreport/.tox/ansible26
ansible26 installdeps: -rrequirements.txt, ansible>=2.6,<2.7, docker==3.4.1
ansible26 installed: ansible==2.6.1,ansible-lint==3.4.23,anyconfig==0.9.4,arrow==0.12.1,asn1crypto==0.24.0,atomicwrites==1.1.5,attrs==18.1.0,backports.functools-lru-cache==1.5,backports.ssl-match-hostname==3.5.0.1,bcrypt==3.1.4,binaryornot==0.4.4,Cerberus==1.2,certifi==2018.4.16,cffi==1.11.5,chardet==3.0.4,click==6.7,click-completion==0.3.1,colorama==0.3.9,configparser==3.5.0,cookiecutter==1.6.0,cryptography==2.2.2,docker==3.4.1,docker-pycreds==0.3.0,enum34==1.1.6,fasteners==0.14.1,flake8==3.5.0,funcsigs==1.0.2,future==0.16.0,git-url-parse==1.1.0,idna==2.7,ipaddress==1.0.22,Jinja2==2.10,jinja2-time==0.2.0,MarkupSafe==1.0,mccabe==0.6.1,molecule==2.16.0,monotonic==1.5,more-itertools==4.2.0,paramiko==2.4.1,pathspec==0.5.6,pbr==4.0.4,pexpect==4.6.0,pluggy==0.6.0,poyo==0.4.1,psutil==5.4.6,ptyprocess==0.6.0,py==1.5.4,pyasn1==0.4.3,pycodestyle==2.3.1,pycparser==2.18,pyflakes==1.6.0,PyNaCl==1.2.1,pytest==3.6.3,python-dateutil==2.7.3,python-gilt==1.2.1,PyYAML==3.13,requests==2.19.1,sh==1.12.14,six==1.11.0,tabulate==0.8.2,testinfra==1.14.0,tree-format==0.1.2,urllib3==1.23,websocket-client==0.48.0,whichcraft==0.4.1,yamllint==1.11.1
```

OS and python:

```
System Version: macOS 10.13.6 (17G65)
Python 2.7.15 (default, Jun 17 2018, 12:46:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
```

## Desired behaviour

The following commands should complete successfully:

```
mkdir ~/tmp
cd ~/tmp
git clone https://github.com/infothrill/molecule-bugreport.git
cd molecule-bugreport
tox
```

### Expected result

All tox tests pass:

```
  py27-ansible24: commands succeeded
  py27-ansible25: commands succeeded
  py27-ansible26: commands succeeded
```

## Actual Behaviour

`tox` tests for `ansible24` and `ansible25` succeed, while `ansible26` fails:

```
  py27-ansible24: commands succeeded
  py27-ansible25: commands succeeded
ERROR:   py27-ansible26: commands failed
```

The full debug output of the failed tasks:

```
    TASK [Destroy molecule instance(s)] ********************************************
    task path: /Users/infothrill/tmp/molecule-bugreport/.tox/ansible26/lib/python3.6/site-packages/molecule/provisioner/ansible/playbooks/docker/destroy.yml:8
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: infothrill
    <127.0.0.1> EXEC /bin/sh -c 'echo ~infothrill && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/infothrill/.ansible/tmp/ansible-tmp-1531643366.879078-120643033411569 `" && echo ansible-tmp-1531643366.879078-120643033411569="` echo /Users/infothrill/.ansible/tmp/ansible-tmp-1531643366.879078-120643033411569 `" ) && sleep 0'
    Using module file /Users/infothrill/tmp/molecule-bugreport/.tox/ansible26/lib/python3.6/site-packages/ansible/modules/cloud/docker/docker_container.py
    <127.0.0.1> PUT /Users/infothrill/.ansible/tmp/ansible-local-41217emtpv0jl/tmpwio4mvkf TO /Users/infothrill/.ansible/tmp/ansible-tmp-1531643366.879078-120643033411569/docker_container.py
    <127.0.0.1> PUT /Users/infothrill/.ansible/tmp/ansible-local-41217emtpv0jl/tmpd37qri64 TO /Users/infothrill/.ansible/tmp/ansible-tmp-1531643366.879078-120643033411569/async_wrapper.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/infothrill/.ansible/tmp/ansible-tmp-1531643366.879078-120643033411569/ /Users/infothrill/.ansible/tmp/ansible-tmp-1531643366.879078-120643033411569/docker_container.py /Users/infothrill/.ansible/tmp/ansible-tmp-1531643366.879078-120643033411569/async_wrapper.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/Users/infothrill/tmp/molecule-bugreport/.tox/ansible26/bin/python3 /Users/infothrill/.ansible/tmp/ansible-tmp-1531643366.879078-120643033411569/async_wrapper.py 328598709749 7200 /Users/infothrill/.ansible/tmp/ansible-tmp-1531643366.879078-120643033411569/docker_container.py _ && sleep 0'
    changed: [localhost] => (item={'name': 'instance', 'image': 'centos:7'}) => {
        "ansible_job_id": "328598709749.41235",
        "changed": true,
        "finished": 0,
        "item": {
            "image": "centos:7",
            "name": "instance"
        },
        "results_file": "/Users/infothrill/.ansible_async/328598709749.41235",
        "started": 1
    }
    changed: [localhost] => {
        "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
        "changed": true
    }

    TASK [Wait for instance(s) deletion to complete] *******************************
    task path: /Users/infothrill/tmp/molecule-bugreport/.tox/ansible26/lib/python3.6/site-packages/molecule/provisioner/ansible/playbooks/docker/destroy.yml:19
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: infothrill
    <127.0.0.1> EXEC /bin/sh -c 'echo ~infothrill && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/infothrill/.ansible/tmp/ansible-tmp-1531643368.2400792-212868659754247 `" && echo ansible-tmp-1531643368.2400792-212868659754247="` echo /Users/infothrill/.ansible/tmp/ansible-tmp-1531643368.2400792-212868659754247 `" ) && sleep 0'
    Using module file /Users/infothrill/tmp/molecule-bugreport/.tox/ansible26/lib/python3.6/site-packages/ansible/modules/utilities/logic/async_status.py
    <127.0.0.1> PUT /Users/infothrill/.ansible/tmp/ansible-local-41217emtpv0jl/tmpngdxn0a6 TO /Users/infothrill/.ansible/tmp/ansible-tmp-1531643368.2400792-212868659754247/async_status.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/infothrill/.ansible/tmp/ansible-tmp-1531643368.2400792-212868659754247/ /Users/infothrill/.ansible/tmp/ansible-tmp-1531643368.2400792-212868659754247/async_status.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/Users/infothrill/tmp/molecule-bugreport/.tox/ansible26/bin/python3 /Users/infothrill/.ansible/tmp/ansible-tmp-1531643368.2400792-212868659754247/async_status.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/infothrill/.ansible/tmp/ansible-tmp-1531643368.2400792-212868659754247/ > /dev/null 2>&1 && sleep 0'
    The full traceback is:
      File "/var/folders/3n/jz7c9xjs6xg4psnmn9ds28k80000gp/T/ansible_6q24d2ap/ansible_modlib.zip/ansible/module_utils/docker_common.py", line 184, in __init__
        super(AnsibleDockerClient, self).__init__(**self._connect_params)
      File "/Users/infothrill/tmp/molecule-bugreport/.tox/ansible26/lib/python3.6/site-packages/docker/api/client.py", line 158, in __init__
        self._version = self._retrieve_server_version()
      File "/Users/infothrill/tmp/molecule-bugreport/.tox/ansible26/lib/python3.6/site-packages/docker/api/client.py", line 183, in _retrieve_server_version
        'Error while fetching server API version: {0}'.format(e)

    failed: [localhost] (item={'started': 1, 'finished': 0, 'ansible_job_id': '328598709749.41235', 'results_file': '/Users/infothrill/.ansible_async/328598709749.41235', '_ansible_parsed': True, 'changed': True, '_ansible_no_log': False, 'failed': False, 'item': {'name': 'instance', 'image': 'centos:7'}, '_ansible_item_result': True, '_ansible_ignore_errors': None, '_ansible_item_label': {'name': 'instance', 'image': 'centos:7'}}) => {
        "ansible_job_id": "328598709749.41235",
        "attempts": 1,
        "changed": false,
        "finished": 1,
        "invocation": {
            "module_args": {
                "api_version": "auto",
                "auto_remove": false,
                "blkio_weight": null,
                "cacert_path": null,
                "capabilities": null,
                "cert_path": null,
                "cleanup": false,
                "command": null,
                "cpu_period": null,
                "cpu_quota": null,
                "cpu_shares": null,
                "cpuset_cpus": null,
                "cpuset_mems": null,
                "debug": false,
                "detach": true,
                "devices": null,
                "dns_opts": null,
                "dns_search_domains": null,
                "dns_servers": null,
                "docker_host": "tcp://192.168.99.100:2376",
                "domainname": null,
                "entrypoint": null,
                "env": null,
                "env_file": null,
                "etc_hosts": null,
                "exposed_ports": null,
                "force_kill": true,
                "groups": null,
                "hostname": null,
                "ignore_image": false,
                "image": null,
                "init": false,
                "interactive": false,
                "ipc_mode": null,
                "keep_volumes": true,
                "kernel_memory": null,
                "key_path": null,
                "kill_signal": null,
                "labels": null,
                "links": null,
                "log_driver": null,
                "log_options": null,
                "mac_address": null,
                "memory": "0",
                "memory_reservation": null,
                "memory_swap": null,
                "memory_swappiness": null,
                "name": "instance",
                "network_mode": null,
                "networks": null,
                "oom_killer": null,
                "oom_score_adj": null,
                "paused": false,
                "pid_mode": null,
                "privileged": false,
                "published_ports": null,
                "pull": false,
                "purge_networks": false,
                "read_only": false,
                "recreate": false,
                "restart": false,
                "restart_policy": null,
                "restart_retries": null,
                "security_opts": null,
                "shm_size": null,
                "ssl_version": "1.0",
                "state": "absent",
                "stop_signal": null,
                "stop_timeout": null,
                "sysctls": null,
                "timeout": 60,
                "tls": false,
                "tls_hostname": "localhost",
                "tls_verify": false,
                "tmpfs": null,
                "trust_image_content": false,
                "tty": false,
                "ulimits": null,
                "user": null,
                "userns_mode": null,
                "uts": null,
                "volume_driver": null,
                "volumes": null,
                "volumes_from": null,
                "working_dir": null
            }
        },
        "item": {
            "ansible_job_id": "328598709749.41235",
            "changed": true,
            "failed": false,
            "finished": 0,
            "item": {
                "image": "centos:7",
                "name": "instance"
            },
            "results_file": "/Users/infothrill/.ansible_async/328598709749.41235",
            "started": 1
        },
        "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', BadStatusLine('\\x15\\x03\\x01\\x00\\x02\\x02\\n',))"
    }
    fatal: [localhost]: FAILED! => {
        "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
        "changed": false
    }

    PLAY RECAP *********************************************************************
    localhost                  : ok=1    changed=1    unreachable=0    failed=1


ERROR:
ERROR: InvocationError for command '/Users/infothrill/tmp/molecule-bugreport/.tox/ansible26/bin/molecule --debug test' (exited with code 2)
___________________________________________________________________________________________________ summary ____________________________________________________________________________________________________
ERROR:   ansible26: commands failed
```

## Attempts to reduce the scope of the error so far

All the following led to no improvement.

* upgraded tox to latest
* ansible 2.6.0 exhibits the same issue
* downgraded `docker` in several steps down to 3.1.1 with no success
* re-provisioned the docker-machine using `docker-machine create -d virtualbox --virtualbox-memory "4096" --virtualbox-cpu-count "3" --virtualbox-disk-size "30000" default`
* Used python interpreter version 3.6.5
* rebooted OS

**Comment by retr0h** [comment] 2018-07-15 16:55
Closing issue as issue reported by @bbaassssiiee is resolved.  Any further issues should get their own issue.  Sorry @infothrill I can't dupe your problem.

**Closed by retr0h** 2018-07-15 16:55 UTC
Labels: question

**Comment by infothrill** [comment] 2018-07-16 13:02
I was able to run molecule successfully by switching from `docker toolbox` to `docker mac`. The underlying issue revolves around [badstatusline docker](https://www.google.de/search?q=badstatusline+docker&oq=badstatusline+docker) and seems to be mysterious to debug at the very least. Thx for your patience and molecule.

**Comment by ssbarnea** [comment] 2018-10-26 17:16
I think that this bug should not be closes as is a real bug with molecule. I was hit by it also and it gave me a very weird first time experience. 

How I sorted it? `pip install -U docker` whici upgraded docker from `2.7.0` to `3.5.1` which worked well. I am not sure which is the minimal version needed but I am sure that molecule would need to have a "docker>=x.y.x" listed as a dependency.

Even if there is a desire not to make docker a permanent dependency, it should list this in extras.

**Comment by lwilke** [comment] 2018-11-01 14:32
We had the same problem. Updating the molecule play (to version from molecule v2.19) for destroying the container fixed the issue for us. We had very old playbooks and were still using these for all our roles b/c we use a cookiecutter template which includes these plays ...

**Comment by wilmardo** [comment] 2018-11-01 16:03
@lwilke You can remove all the playbooks except `playbook.yml` if you are using the default playbooks for Docker :)

**Comment by lwilke** [comment] 2018-11-02 12:06
Yes, this is correct. Without your own plays the defaults are used. Just wanted to mention it. Esp. in case you have local modifications to the default plays.

**Comment by marverix** [comment] 2020-05-09 06:26
I have the same issue...
```
$ pip freeze | egrep "(molecule|ansible|docker)"
ansible==2.8.11
ansible-lint==4.2.0
docker==4.2.0
docker-compose==1.25.4
docker-py==1.10.6
docker-pycreds==0.4.0
dockerpty==0.4.1
molecule==3.0.4
```
