### ISSUE TITLE
[Bug] UnicodeDecodeError (molecule/util.py) when using verbose=v (or vv ...) on (ansible) large output

### ISSUE THREAD

**Issue by lhoss** [metacloud/molecule#702] opened 2017-01-09 10:41 UTC
# Issue Type
- Bug report

# Molecule and Ansible details
```
# ansible --version
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
# molecule --version
molecule, version 1.17.3
```
- Molecule installation method: pip
- Ansible installation method:  pip

# Actual Behaviour (Bug report only)
Molecule just hangs, after it outputed following  error, during my ansible playbook was deploying openjdk-8 (in ubuntu-14.04 using a ppa), and when using molecule's config `verbose: vv`.
It seems like the output somehow contains special chars (the output is also quite large) (I removed part in the middle):

```
TASK [lhoss.java : Ensure Java is installed.] **********************************
task path: /Users/lhoss/IdeaProjects/ansible-zookeeper/.molecule/roles/lhoss.java/tasks/setup-Debian.yml:15
The following additional packages will be installed:
  ca-certificates ca-certificates-java dbus dbus-x11 fontconfig
  fontconfig-config fonts-dejavu-core fonts-dejavu-extra gconf-service
  gconf-service-backend gconf2 gconf2-common hicolor-icon-theme java-common
  krb5-locales libasn1-8-heimdal libasound2 libasound2-data libasyncns0
  libatk1.0-0 libatk1.0-data libavahi-client3 libavahi-common-data
  libavahi-common3 libavahi-glib1 libbonobo2-0 libbonobo2-common libbsd0
  libcairo2 libcanberra0 libcap-ng0 libcups2 libdatrie1 libdbus-1-3
  libdbus-glib-1-2 libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 libedit2 libelf1 libflac8 libfontconfig1 libfreetype6 libgconf-2-4
  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgif7 libgl1-mesa-dri
  libgl1-mesa-glx libglapi-mesa libglib2.0-0 libglib2.0-data libgmp10
  libgnome-2-0 libgnome2-common libgnomevfs2-0 libgnomevfs2-common libgnutls30
  libgraphite2-3 libgssapi-krb5-2 libgssapi3-heimdal libgtk2.0-0 libgtk2.0-bin
  libgtk2.0-common libharfbuzz0b libhcrypto4-heimdal libheimbase1-heimdal
  libheimntlm0-heimdal libhogweed4 libhx509-5-heimdal libice-dev libice6
  libicu55 libidn11 libjbig0 libjpeg-turbo8 libjpeg8 libjson-c2 libk5crypto3
  libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0 liblcms2-2
  libldap-2.4-2 libllvm3.8 libltdl7 libnettle6 libnspr4 libnss3 libnss3-nssdb
  libogg0 liborbit-2-0 libp11-kit0 libpango-1.0-0 libpangocairo-1.0-0
  libpangoft2-1.0-0 libpciaccess0 libpcsclite1 libpixman-1-0 libpng12-0
  libpopt0 libpthread-stubs0-dev libpulse0 libroken18-heimdal libsasl2-2
  libsasl2-modules libsasl2-modules-db libsm-dev libsm6 libsndfile1 libtasn1-6
  libtdb1 libthai-data libthai0 libtiff5 libtxc-dxtn-s2tc0 libvorbis0a
  libvorbisenc2 libvorbisfile3 libwind0-heimdal libwrap0 libx11-6 libx11-data
  libx11-dev libx11-doc libx11-xcb1 libxau-dev libxau6 libxcb-dri2-0
  libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-render0 libxcb-shm0
  libxcb-sync1 libxcb1 libxcb1-dev libxcomposite1 libxcursor1 libxdamage1
  libxdmcp-dev libxdmcp6 libxext6 libxfixes3 libxi6 libxinerama1 libxml2
  libxrandr2 libxrender1 libxshmfence1 libxt-dev libxt6 libxtst6 libxxf86vm1
  openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless openssl psmisc
  sgml-base shared-mime-info sound-theme-freedesktop tcpd ucf x11-common
  x11proto-core-dev x11proto-input-dev x11proto-kb-dev xdg-user-dirs xml-core
  xorg-sgml-doctools xtrans-dev
Suggested packages:
  gconf-defaults-service default-jre libasound2-plugins alsa-utils
  libbonobo2-bin libcanberra-gtk0 libcanberra-pulse cups-common desktop-base
  libgnomevfs2-bin libgnomevfs2-extra gamin | fam gnome-mime-data gnutls-bin
  krb5-doc krb5-user librsvg2-common gvfs libice-doc liblcms2-utils pciutils
  pcscd pulseaudio libsasl2-modules-otp libsasl2-modules-ldap
  libsasl2-modules-sql libsasl2-modules-gssapi-mit
  | libsasl2-modules-gssapi-heimdal libsm-doc libxcb-doc libxt-doc
  openjdk-8-demo openjdk-8-source visualvm icedtea-8-plugin
  openjdk-8-jre-jamvm libnss-mdns fonts-ipafont-gothic fonts-ipafont-mincho
  ttf-wqy-microhei | ttf-wqy-zenhei fonts-indic sgml-base-doc debhelper
The following NEW packages will be installed:
  ca-certificates ca-certificates-java dbus dbus-x11 fontconfig
  fontconfig-config fonts-dejavu-core fonts-dejavu-extra gconf-service
  gconf-service-backend gconf2 gconf2-common hicolor-icon-theme java-common
  krb5-locales libasn1-8-heimdal libasound2 libasound2-data libasyncns0
  libatk1.0-0 libatk1.0-data libavahi-client3 libavahi-common-data
  libavahi-common3 libavahi-glib1 libbonobo2-0 libbonobo2-common libbsd0
  libcairo2 libcanberra0 libcap-ng0 libcups2 libdatrie1 libdbus-1-3
  libdbus-glib-1-2 libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 libedit2 libelf1 libflac8 libfontconfig1 libfreetype6 libgconf-2-4
  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgif7 libgl1-mesa-dri
  libgl1-mesa-glx libglapi-mesa libglib2.0-0 libglib2.0-data libgmp10
  libgnome-2-0 libgnome2-common libgnomevfs2-0 libgnomevfs2-common libgnutls30
  libgraphite2-3 libgssapi-krb5-2 libgssapi3-heimdal libgtk2.0-0 libgtk2.0-bin
  libgtk2.0-common libharfbuzz0b libhcrypto4-heimdal libheimbase1-heimdal
  libheimntlm0-heimdal libhogweed4 libhx509-5-heimdal libice-dev libice6
  libicu55 libidn11 libjbig0 libjpeg-turbo8 libjpeg8 libjson-c2 libk5crypto3
  libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0 liblcms2-2
  libldap-2.4-2 libllvm3.8 libltdl7 libnettle6 libnspr4 libnss3 libnss3-nssdb
  libogg0 liborbit-2-0 libp11-kit0 libpango-1.0-0 libpangocairo-1.0-0
  libpangoft2-1.0-0 libpciaccess0 libpcsclite1 libpixman-1-0 libpng12-0
  libpopt0 libpthread-stubs0-dev libpulse0 libroken18-heimdal libsasl2-2
  libsasl2-modules libsasl2-modules-db libsm-dev libsm6 libsndfile1 libtasn1-6
  libtdb1 libthai-data libthai0 libtiff5 libtxc-dxtn-s2tc0 libvorbis0a
  libvorbisenc2 libvorbisfile3 libwind0-heimdal libwrap0 libx11-6 libx11-data
  libx11-dev libx11-doc libx11-xcb1 libxau-dev libxau6 libxcb-dri2-0
  libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-render0 libxcb-shm0
  libxcb-sync1 libxcb1 libxcb1-dev libxcomposite1 libxcursor1 libxdamage1
  libxdmcp-dev libxdmcp6 libxext6 libxfixes3 libxi6 libxinerama1 libxml2
  libxrandr2 libxrender1 libxshmfence1 libxt-dev libxt6 libxtst6 libxxf86vm1
  openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless
  openssl psmisc sgml-base shared-mime-info sound-theme-freedesktop tcpd ucf
  x11-common x11proto-core-dev x11proto-input-dev x11proto-kb-dev
  xdg-user-dirs xml-core xorg-sgml-doctools xtrans-dev
0 upgraded, 176 newly installed, 0 to remove and 20 not upgraded.

changed: [zookeeper02] => (item=[u'openjdk-8-jdk']) => {"cache_update_time": 1483956303, "cache_updated": false, "changed": true, "item": ["openjdk-8-jdk"], "stderr": "\rExtracting templates from packages: 13%\rExtracting templates from packages: 27%\rExtracting templates from packages: 40%\rExtracting templates from packages: 54%\rExtracting templates from packages: 67%\rExtracting templates from packages: 81%\rExtracting templates from packages: 95%\rExtracting templates from packages: 100%\nupdate-initramfs: deferring update (trigger activated)\n * Setting up X socket directories...\n   ...done.\n\nCreating config file /etc/gconf/2/path with new version\n\n(gconftool-2:5254): GConf-WARNING **: Client failed to connect to the D-BUS daemon:\nUnable to autolaunch a dbus-daemon without a $DISPLAY for X11\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following extra packages will be installed:\n  acl at-spi2-core ca-certificates-java colord cpp cp
p-4.8 dbus dbus-x11\n  dconf-gsettings-backend dconf-service desktop-file-utils dosfstools\n  fontconfig fontconfig-config fonts-dejavu-core fonts-dejavu-extra fuse\n  gcc-4.8-base gconf-service gconf-service-ba

...

auto mode", "update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/xjc to provide /usr/bin/xjc (xjc) in auto mode", "Setting up openjdk-8-jdk:amd64 (8u111-b14-3~14.04.1) ...", "update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/appletviewer to provide /usr/bin/appletviewer (appletviewer) in auto mode", "update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode", "Setting up ca-certificates-java (20130815ubuntu1) ...", "Adding debian:Entrust.net_Premium_2048_Secure_Server_CA.pem", "Adding debian:A-Trust-
nQual-03.pem", "Adding debian:AffirmTrust_Commercial.pem", "Adding debian:SwissSign_Platinum_CA_-_G2.pem", "Adding debian:China_Internet_Network_Information_Center_EV_Certificates_Root.pem", "Adding debian:TWCA_Root_Certification_Authority.pem", "Adding debian:Visa_eCommerce_Root.pem", "Adding debian:GlobalSign_Root_CA.pem", "Adding debian:NetLock_Business_=Class_B=_Root.pem", "Adding debian:AddTrust_External_Root.pem", "Adding debian:Equifax_Secure_CA.pem", "Adding debian:VeriSign_Class_3_Public_Primary_Certification_Authority_-_G5.pem", "Adding debian:QuoVadis_Root_CA_3_G3.pem", "Adding debian:thawte_Primary_Root_CA_-_G3.pem", "Adding debian:GlobalSign_Root_CA_-_R3.pem", "Adding debian:Go_Daddy_Class_2_CA.pem", "Adding debian:D-TRUST_Root_Class_3_CA_2_EV_2009.pem", "Adding debian:Comodo_Secure_Services_root.pem", "Adding debian:UTN_USERFirst_Hardware_Root_CA.pem", "Adding debian:DST_ACES_CA_X6.pem", "Adding debian:Digital_Signature_Trust_Co._Global_CA_1.pem", "Adding debian:Root_CA_Generalitat_Valenciana.pe
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/miniconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/miniconda2/lib/python2.7/site-packages/sh.py", line 1484, in output_thread
    done = stream.read()
  File "/usr/local/miniconda2/lib/python2.7/site-packages/sh.py", line 1974, in read
    self.write_chunk(chunk)
  File "/usr/local/miniconda2/lib/python2.7/site-packages/sh.py", line 1949, in write_chunk
    self.should_quit = self.process_chunk(chunk)
  File "/usr/local/miniconda2/lib/python2.7/site-packages/sh.py", line 1867, in process
    return handler(chunk)
  File "/usr/local/miniconda2/lib/python2.7/site-packages/sh.py", line 1106, in fn
    return handler(chunk, *args)
  File "/usr/local/miniconda2/lib/python2.7/site-packages/molecule/util.py", line 81, in callback_info
    print_info(msg, pretty=False)
  File "/usr/local/miniconda2/lib/python2.7/site-packages/molecule/util.py", line 45, in print_info
    print_msg('{}', msg)
  File "/usr/local/miniconda2/lib/python2.7/site-packages/molecule/util.py", line 76, in print_msg
    print(template.format(msg.rstrip().encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 976: ordinal not in range(128)


```
Note: It works with `verbose: False` (as the bad output is simply omitted)

**Comment by retr0h** [comment] 2017-01-24 17:12
Haven't had a chance to look into this yet.  Anyone have ideas?

**Comment by retr0h** [comment] 2017-01-29 00:07
Reproducible via #727

> Here is a reproducible test in an isolated repo to aid in debugging: https://github.com/conorsch/molecule-diff-encoding-bug

**Comment by retr0h** [comment] 2017-04-26 18:54
I cannot reproduce this issue on my system.

```
[jodewey:~/git/molecule/test/foo] [molecule-env-2.7.12] master+* ± ansible --version
moansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Jan 28 2017, 16:17:28) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
[jodewey:~/git/molecule/test/foo] [molecule-env-2.7.12] master+* ± molecule --version
molecule, version 1.24.0
[jodewey:~/git/molecule/test/foo] [molecule-env-2.7.12] master+* ± echo $LANG
en_US.UTF-8
[jodewey:~/git/molecule/test/foo] [molecule-env-2.7.12] master+* ±
```

**Comment by retr0h** [comment] 2017-04-27 19:50
Unable to duplicate.  Need more info.  Closing.  Please reopen if still an issue. Molecule v2 uses logger, which hopefully doesn't suffer from this same fate.

**Closed by retr0h** 2017-04-27 19:50 UTC
Labels: bug, help wanted
