### ISSUE TITLE
Failure to discover local Docker images

### ISSUE THREAD

**Issue by Squick1** [metacloud/molecule#1383] opened 2018-07-11 17:53 UTC
# Issue Type

- Bug report

# Molecule and Ansible details
```
ansible --version
ansible 2.6.1
  config file = None
  configured module search path = [u'/Users/jpereira/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 14:43:05) [GCC 4.2.1 Compatible 

```

```
molecule --version
molecule, version 2.16.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- brew

# Desired Behavior

Trying to run and ssh into a basic role created through molecule.

# Actual Behaviour (Bug report only)

```
TASK [Discover local Docker images] ********************************************
    failed: [localhost] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
```
I receive this error when I input molecule converge into terminal

**Comment by retr0h** [comment] 2018-07-14 00:29
I can't really help you based on the information provided.  Please run molecule --debug and provide appropriate details.

**Comment by Uwila** [comment] 2018-07-15 07:37
You're not giving a lot of info of what you're doing specifically, but based on the title I think this might be a duplicate of #1234 . In summary: In the `create.yml` playbook, which is used to create an instance, the `docker_image` module is used. Setting `pull: false` would perhaps solve the issue.

**Closed** 2018-07-15 12:59 UTC
Labels: question

**Comment by alainchiasson-guavus** [comment] 2018-07-29 16:05
As a quick note for others who may bump into this, the error is hidden by the "censored" output. In my case, it was not the `pull: false` issue but the fact that I was missing the pip`docker` or `docker-py` requirement for molecule. 

This was a fresh install - so I was going from memory (bad me).

**Comment by vignajethkk** [comment] 2019-04-22 12:21
```
docker --version
Docker version 18.09.0, build 4d60db4
molecule --version
molecule, version 2.20.0
ansible --version
ansible 2.8.0a1
config file = /etc/ansible/ansible.cfg
configured module search path = ['/Users/user_name/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
```

my molecule.yml has 
```
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
    pull: False
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
```
Error i get
```
TASK [Discover local Docker images] ********************************************
    failed: [localhost] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
```

**Comment by decentral1se** [comment] 2019-04-23 10:14
> is there a way to override no_log:true ??

@vignajethkk, pass `--debug` to your molecule invocation :+1:

**Comment by bbaassssiiee** [comment] 2019-07-15 21:25
`pip install docker`
