### ISSUE TITLE
UnicodeDecodeError when issuing molecule init

### ISSUE THREAD

**Issue by davidfischer-ch** [metacloud/molecule#796] opened 2017-04-02 12:08 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
Ubuntu 16.04 LTS 64 bits
Ansible 2.3.0.0
  config file = /mnt/extra/decrypt/david-develop/ansible-roles/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Molecule, version 1.23.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behavior

```
git clone https://github.com/davidfischer-ch/ansible-roles.git
cd ansible-roles/
molecule --debug init
--> Initializing molecule in current directory...
... (all OK)
```

# Current Behavior

```
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/init.py", line 141, in init
    util.sysexit(i.execute()[0])
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/init.py", line 53, in execute
    self._init_existing_role(role, role_path, driver, verifier)
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/init.py", line 75, in _init_existing_role
    util.process_templates(template, extra_context, role_path)
  File "/usr/local/lib/python2.7/dist-packages/molecule/util.py", line 115, in process_templates
    no_input=True, )
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/main.py", line 144, in cookiecutter
    output_dir=output_dir
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/generate.py", line 350, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/generate.py", line 168, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 1: invalid continuation byte
```

**Comment by t2d** [comment] 2017-04-18 20:25
You should use `molecule init` in the directory of a role (e.g. https://github.com/davidfischer-ch/ansible-roles/tree/master/roles/fail2ban), not in a directory containing roles.

**Comment by davidfischer-ch** [comment] 2017-04-26 15:24
OK. Do you think its possible and what is the best practice to write "integration" testing multiples roles together with?

Thanks.

**Comment by retr0h** [comment] 2017-04-26 18:28
@davidfischer-ch can you provide more details as to where you are running `molecule init` from?  I cannot reproduce this issue.  What is your shells LANG environment variable?

**Comment by retr0h** [comment] 2017-04-27 19:50
Unable to duplicate.  Need more info.  Closing.  Please reopen if still an issue. Molecule v2 uses logger, which hopefully doesn't suffer from this same fate.

**Closed by retr0h** 2017-04-27 19:50 UTC
Labels: question
