### ISSUE TITLE
Clean install, problem with Vagrant on OSX

### ISSUE THREAD

**Issue by damianoneill** [metacloud/molecule#1157] opened 2018-02-24 13:11 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.3.0
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

molecule, version 2.9.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Please give some details of the feature being requested or what
should happen if providing a bug report.

# Actual Behaviour (Bug report only)

```
$ virtualenv --no-site-packages .venv
$ source .venv/bin/activate
$ pip install molecule ansible
$ pip install python-vagrant docker-py
$ molecule init role -r chrony -d vagrant
$ cd chrony
$ molecule test 

...

TASK [Populate instance config dict] *******************************************
    fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'IdentityFile'\n\nThe error appears to have been in '/Users/doneill/Downloads/chrony/molecule/default/create.yml': line 38, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Populate instance config dict\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'IdentityFile'"}

...

```

**Comment by antoniokaust** [comment] 2018-02-24 18:18
I have the same configuration and the same problem.

**Comment by retr0h** [comment] 2018-02-24 19:17
I can't reproduce with the same version of ansible and molecule.  What version of Vagrant are you using and python-vagrant?

**Comment by retr0h** [comment] 2018-02-24 19:34
Upgraded to Vagrant 2.0.2 and have no issues either.

```
[jodewey:/tmp/test] [.venv] % vagrant --version
Vagrant 2.0.2
```

**Comment by damianoneill** [comment] 2018-02-24 19:46
$ vagrant --version
Vagrant 2.0.2
(.venv)
$ pip freeze | grep python-vagrant
python-vagrant==0.5.15
(.venv)

**Comment by antoniokaust** [comment] 2018-02-24 20:11
$ vagrant --version
Vagrant 2.0.2
$ pip freeze | grep python-vagrant
python-vagrant==0.5.15


The only thing that changed from when it was working to now was macOS High Sierra update to version 10.13.3, i.e. latest security upgrade.


I fixed this issue it by uninstalling Vagrant which wasn't returning IdentityFile when running vagrant ssh-config in its output. I reinstalled version 2.0.2 and business as normal again.


Ciao,

--
Antonio Arena | Research Applications Lead
Building 14 | Level 4 | R401-WS35
King Abdullah University of Science and Technology
O: +966 (2) 808-1286 | M: +966 (0)56-898-4501


________________________________

**Comment by retr0h** [comment] 2018-02-24 20:13
Odd

**Comment by damianoneill** [comment] 2018-02-26 13:44
I tried @antoniokaust suggestion, on my solution vagrant is installed with homebrew, I've removed and re-installed, problem still exists.

**Comment by retr0h** [comment] 2018-03-01 16:26
Do you have something in `~/.vagrant.d/Vagrantfile`?

**Comment by retr0h** [comment] 2018-03-07 17:57
Duplicate of #1161.  See for discussion and proposed fixes/work-a-rounds.

**Closed by retr0h** 2018-03-07 17:57 UTC

**Comment by retr0h** [comment] 2018-03-07 20:51
v2.10 was cut to fix this issue.
