### ISSUE TITLE
[question] Ansible changes in molecule 1.12 ?

### ISSUE THREAD

**Issue by milosgajdos83** [metacloud/molecule#551] opened 2016-10-12 17:32 UTC
I'm wondering if there have been any significant changes regarding `Ansible` code in the latest release.

We started noticing a strange behaviour when restarting services i.e. regarding `service` Ansible core module when during `converge` phase `molecule` just hangs infinitely on service starts and restarts.

The role `YAML` we use for testing `zookeeper` can be found [here](https://gist.github.com/milosgajdos83/326dc4f5b04c9ca6bcdbf3de8f507d3f) and the task `molecule` hangs on is here:

```
TASK [ansible-zookeeper : Initizalize ZooKeeper] *******************************
changed: [zk01]

TASK [ansible-zookeeper : Start ZooKeeper service] *****************************

```

What's strange is that when I `docker exec` into the test container and check if the service is running, it actually is:

```
$ docker exec -it zk01 /etc/init.d/zookeeper-server status
zookeeper-server is running
```

This role executes perfectly fine on our servers, but hangs when tested using molecule. My understanding is that `molecule` imports `Ansible` via library, so I'm wondering about what may have changed that could have caused this change of behaviour :-/

Any ideas?

**Comment by retr0h** [comment] 2016-10-12 17:40
> This role executes perfectly fine on our servers, but hangs when tested using molecule. My understanding is that molecule imports Ansible via library, so I'm wondering about what may have changed that could have caused this change of behaviour :-/

@milosgajdos83 I'll look into this.  However, molecule doesn't do anything with ansible internally.  It simply executes an `ansible-playbook` CLI command just as a user would.

**Comment by milosgajdos83** [comment] 2016-10-12 18:03
Thanks!

I'm totally puzzled by this -- we will probably downgrade to older version of `molecule`, although we did upgrade ansible too:

```
$ pip show ansible
---
Metadata-Version: 2.0
Name: ansible
Version: 2.1.2.0
Summary: Radically simple IT automation
Home-page: http://ansible.com/
Author: Ansible, Inc.
Author-email: support@ansible.com
Installer: pip
License: GPLv3
Location: /Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages
Requires: paramiko, pycrypto, PyYAML, setuptools, jinja2
Classifiers:
  Development Status :: 5 - Production/Stable
  Environment :: Console
  Intended Audience :: Developers
  Intended Audience :: Information Technology
  Intended Audience :: System Administrators
  License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
  Natural Language :: English
  Operating System :: POSIX
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Topic :: System :: Installation/Setup
  Topic :: System :: Systems Administration
  Topic :: Utilities
```

Let me know if I can help out with anything .

**Comment by retr0h** [comment] 2016-10-12 18:13
Can you upload your role to github, the gist you provided is incomplete.

**Comment by milosgajdos83** [comment] 2016-10-12 23:05
I've updated the gist with all the files -- unfortunately can't stick it to my GH repos and will have to remove the gist at some point :-/

The whole role should now be there -- albeit sadly not in one simple repo.

**Comment by retr0h** [comment] 2016-10-12 23:09
> although we did upgrade ansible too:

What version did you upgrade to?  Obviously you were not using Ansible 1.9 since it doesn't work with docker.

**Comment by milosgajdos83** [comment] 2016-10-12 23:12
We upgraded from `2.1.1.0` to `2.1.2.0`.

**Comment by retr0h** [comment] 2016-10-12 23:21
I get the following error with what you provided:

```
TASK [zookeeper : Initizalize ZooKeeper] ***************************************
fatal: [zk01]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: sorry, you must have a tty to run sudo\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by retr0h** [comment] 2016-10-13 00:38
@milosgajdos83 the problem is with the zookeeper init script.  It is leaving stdout and/or stderr open which hangs ansible.

It can be reproduced by simply restarting the service and trying to exit the container.

```
[jodewey:/private/tmp/zookeeper] % docker exec -it zk01 bash
[root@421f5f61aee9 /]# /etc/init.d/zookeeper-server restart
Restarting ZooKeeper daemon: JMX enabled by default
Using config: /etc/zookeeper/conf/zoo.cfg
Stopping zookeeper ... STOPPED
[root@421f5f61aee9 /]# exit
```

I would suggest looking at the init script or using one of the existing zookeeper galaxy roles.

**Comment by milosgajdos83** [comment] 2016-10-13 08:04
Maybe. I need to test your theory :-)

It doesn't explain why everything works fine when we are setting up the actual servers, though. It also doesn't explain why was this working perfectly fine on the previous version. Saying that, you might be totally correct. I'll give this a spin today. Thanks for looking into this, I'll report back.

M

**Comment by milosgajdos83** [comment] 2016-10-13 10:51
Hi! Yes! I have reproduced the hanging exit from docker containers following your suggestion i.e. when I `docker exec` in the container and try to restart zk service I can't exit the container any more :-/

I tested the same test playbook using `vagrant` provider and everything works fine. So I'm thinking It might actually be related to `docker` on Mac. I need to investigate this.

**Comment by retr0h** [comment] 2016-10-14 20:35
Closing as not a direct issue of molecule.

**Closed by retr0h** 2016-10-14 20:35 UTC
Labels: question
