### ISSUE TITLE
Molecule not finding Python Docker driver

### ISSUE THREAD

**Issue by mschuchard** [metacloud/molecule#920] opened 2017-08-14 20:50 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version: 2.3.1
molecule --version: 1.25.0
docker version 1.12.6
docker python sdk version 2.4.2
OS version RHEL 7.4
```

- Molecule installation method: pip
- Ansible installation method: OS Package from Tower
- Docker installation: os package
- Docker Python SDK installation: pip

# Desired Behaviour

Molecule use the Python Docker SDK bindings during a test.

# Actual Behaviour (Bug report only)

> Error: python docker drive missing, install the docker package

**Comment by retr0h** [comment] 2017-08-14 21:08
Right, you need to install it :)

`pip install docker`

**Comment by mschuchard** [comment] 2017-08-14 22:49
As stated in the issue above, we already installed the docker sdk binding with `pip`. The issue also goes beyond what was asked in the template and rpovides extra information beyond what was requested.

**Comment by retr0h** [comment] 2017-08-15 00:17
It's a simple [try/catch around the import of docker](https://github.com/metacloud/molecule/blob/v1/molecule/driver/dockerdriver.py#L26-L30).  I can't reproduce the issue.

```
[jodewey:~/git/molecule/test/scenarios/command_test] [molecule-env-2.7.13] v1+ ± molecule test --driver docker
ERROR: python docker driver missing, install the docker package.
[jodewey:~/git/molecule/test/scenarios/command_test] [molecule-env-2.7.13] v1+ 1 ± pip install docker -U
Collecting docker
  Using cached docker-2.4.2-py2.py3-none-any.whl
Requirement already up-to-date: six>=1.4.0 in /Users/jodewey/.pyenv/versions/2.7.13/envs/molecule-env-2.7.13/lib/python2.7/site-packages (from docker)
Collecting requests!=2.11.0,!=2.12.2,!=2.18.0,>=2.5.2 (from docker)
  Using cached requests-2.18.3-py2.py3-none-any.whl
Requirement already up-to-date: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /Users/jodewey/.pyenv/versions/2.7.13/envs/molecule-env-2.7.13/lib/python2.7/site-packages (from docker)
Requirement already up-to-date: ipaddress>=1.0.16; python_version < "3.3" in /Users/jodewey/.pyenv/versions/2.7.13/envs/molecule-env-2.7.13/lib/python2.7/site-packages (from docker)
Collecting websocket-client>=0.32.0 (from docker)
  Using cached websocket_client-0.44.0-py2.py3-none-any.whl
Requirement already up-to-date: docker-pycreds>=0.2.1 in /Users/jodewey/.pyenv/versions/2.7.13/envs/molecule-env-2.7.13/lib/python2.7/site-packages (from docker)
Collecting certifi>=2017.4.17 (from requests!=2.11.0,!=2.12.2,!=2.18.0,>=2.5.2->docker)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests!=2.11.0,!=2.12.2,!=2.18.0,>=2.5.2->docker)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests!=2.11.0,!=2.12.2,!=2.18.0,>=2.5.2->docker)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Requirement already up-to-date: idna<2.6,>=2.5 in /Users/jodewey/.pyenv/versions/2.7.13/envs/molecule-env-2.7.13/lib/python2.7/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,>=2.5.2->docker)
Installing collected packages: certifi, chardet, urllib3, requests, websocket-client, docker
  Found existing installation: chardet 3.0.2
    Uninstalling chardet-3.0.2:
      Successfully uninstalled chardet-3.0.2
  Found existing installation: requests 2.13.0
    Uninstalling requests-2.13.0:
      Successfully uninstalled requests-2.13.0
  Found existing installation: websocket-client 0.40.0
    Uninstalling websocket-client-0.40.0:
      Successfully uninstalled websocket-client-0.40.0
  Found existing installation: docker 2.2.1
    Uninstalling docker-2.2.1:
      Successfully uninstalled docker-2.2.1
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 docker-2.4.2 requests-2.18.3 urllib3-1.22 websocket-client-0.44.0
[jodewey:~/git/molecule/test/scenarios/command_test] [molecule-env-2.7.13] v1+ ± molecule test --driver docker
--> Destroying instances...
--> Checking playbook's syntax...

playbook: playbook.yml
--> Creating instances...
--> Creating Ansible compatible image of ubuntu:latest ...
--> Building ansible compatible image...
	Step 1/8 : FROM ubuntu:latest
	Pulling fs layer ...
	Waiting ...
	Downloading ...
	Verifying Checksum ...
	Download complete ...
	Downloading ...
	Verifying Checksum ...
	Download complete ...
	Downloading ...
	Verifying Checksum ...
	Download complete ...
	Downloading ...
	Verifying Checksum ...
	Download complete ...
	Downloading ...
	Download complete ...
	Extracting ...
	Pull complete ...
	Extracting ...
	Pull complete ...
	Extracting ...
	Pull complete ...
	Extracting ...
	Pull complete ...
	Extracting ...
	Pull complete ...
	Digest: sha256:34471448724419596ca4e890496d375801de21b0e67b81a77fd6155ce001edad ...
	Status: Downloaded newer image for ubuntu:latest ...
	 ---> ccc7a11d65b1
	Step 2/8 : RUN /bin/sh -c 'if [ -x "$(command -v apt-get)" ]; then apt-get update && apt-get install -y python sudo bash; fi'
	 ---> Running in d41583d012cf
	Get:1 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
	Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
	Get:3 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [43.9 kB]
	Get:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [426 kB]
	Get:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
	Get:6 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.8 kB]
	Get:7 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [191 kB]
	Get:8 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [2935 B]
	Get:9 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
	Get:10 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9802 kB]
	Get:11 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
	Get:12 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
	Get:13 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
	Get:14 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
	Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [210 kB]
	Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [784 kB]
	Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.3 kB]
	Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [652 kB]
	Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [17.5 kB]
	Get:20 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [4934 B]
	Get:21 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [6236 B]
	Fetched 24.3 MB in 19s (1261 kB/s)
Reading package lists...
```

```
[jodewey:~/git/molecule/test/scenarios/command_test] [molecule-env-2.7.13] v1+ 2 ± pip freeze | grep docker
docker==2.4.2
docker-pycreds==0.2.1
```

I would double check your python environment is setup properly.  Molecule is doing nothing special but an import.

**Comment by mschuchard** [comment] 2017-08-15 01:22
Thanks for the non-reproducibility proof. We will double-check the environment tomorrow, as that does seem the most likely explanation.

Did you test that on a RHEL 7.4 env by any chance (a CentOS 7.4 Vagrant instance, for example, would be the same as far as I am concerned)?

**Comment by mschuchard** [comment] 2017-08-15 15:36
So we figured out the issue. The exception message was assuming that the failure to import the docker module meant that it was not installed. We did a simple python script to import docker and discovered in the stack trace that what actually was failing was the import of a dependency lower down the chain. We updated/reinstalled dependencies iteratively to work it out, since the dependencies installed for the docker sdk bindings were not accurate for what was actually required.

Could you please update the exception message to expand to our situation so in the future people will know the problem may be something else?

**Comment by retr0h** [comment] 2017-08-15 16:35
Can you provide the details as to what was missing?

**Comment by retr0h** [comment] 2017-08-15 16:37
If molecule was installed using pip then molecule's dependencies will be installed.  However, molecule does require you to install the driver dependencies.  By running pip install docker you should get all of those dependencies installed.  I'm thinking a pip install -U docker would have corrected any issue you had with docker's deps.

**Comment by mschuchard** [comment] 2017-08-16 13:44
As noted above, the basic installation procedure was installing docker via `yum`, ansible via package from a tower install, molecule via `pip`, and docker (python sdk bindings) via `pip`. Doing `pip install docker` did pick up its dependencies, but python failed to find them until we reinstalled all of them.

In any case, the point is there is no bug with molecule here, just an exception message that was inaccurate for our situation.

**Comment by retr0h** [comment] 2017-08-16 15:18
Closing. currently satisfied with the level of error reporting in Molecule.  Others can reference this issue, if they run across this problem.  Will reevaluate my decision in the future, if this becomes a more prominent problem.

**Closed by retr0h** 2017-08-16 15:18 UTC
Labels: question

**Comment by ryanhartje** [comment] 2019-12-05 19:24
I'm running into this, as is:
https://www.503error.com/2019/molecule%E7%AE%80%E4%BB%8B/1657.html

It's difficult to pin down what exactly is missing, I've reinstalled the docker pywheel without success.

**Comment by fred-drake** [comment] 2023-12-25 05:11
For anybody finding this in a google search, `pip install docker` didn't do it, but `pip install molecule-plugins` did.

**Comment by kenorb** [comment] 2024-06-13 15:53
For Molecule 5+:

```console
pip install 'molecule-plugins[docker]'
```
