### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by dfinninger** [metacloud/molecule#1070] opened 2017-12-19 17:45 UTC
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.4.2.0
  config file = /Users/dfinninger/.ansible.cfg
  configured module search path = ['/Users/dfinninger/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dfinninger/.virtualenvs/infra-py3/lib/python3.6/site-packages/ansible
  executable location = /Users/dfinninger/.virtualenvs/infra-py3/bin/ansible
  python version = 3.6.3 (default, Oct  4 2017, 06:09:15) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]

molecule, version 2.5.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Ability to use Python 3

# Actual Behaviour (Bug report only)

```
$ molecule --debug init
ERROR: Python version '3.6.3' not supported.  Molecule only supports python version = 2.7.

$ molecule --no-debug init
ERROR: Python version '3.6.3' not supported.  Molecule only supports python version = 2.7.

$ molecule init
ERROR: Python version '3.6.3' not supported.  Molecule only supports python version = 2.7.
```

# Additional Discussion

Is there a reason for explicitly blocking Python 3 from molecule?
It looks like [the CLI code](https://github.com/metacloud/molecule/blob/2.5/molecule/shell.py#L61-L64) explicitly disables Python 3.6. The [CHANGELOG](https://github.com/metacloud/molecule/blob/master/CHANGELOG.rst#23) mentions that version checks were added and the associated [pull request](https://github.com/metacloud/molecule/pull/990/commits/4a1af54f804ef6006e27ba855ff5a90ff11d1071) doesn't shed much light on the decision either.

Is there a particular rationale for this? I've searched through the docs (and maybe I missed it) but I couldn't find anywhere that states why this is blocked. 

#763 states that Molecule v2 is 3.5/3.6 compliant.

A note in the documentation about this or removing the constraint would be greatly appreciated. If work is needed to support Python3, then I can try to devote some cycles over the holidays.

**Comment by retr0h** [comment] 2017-12-20 23:28
The problem is Ansible _not_ Molecule.  I have been trying to release py3 support for Molecule since Ansible 2.2.  However, Molecule always finds a bug with Ansible's py3 comparability. 

Last [bug reported](https://github.com/ansible/ansible/issues/32301) had to do with galaxy having issues under py3.

**Comment by dfinninger** [comment] 2017-12-20 23:42
@retr0h Thanks for the response. I'm in the process of upgrading Molecule for our team and wanted to try out Python 3. But if it's a problem with Ansible than that's all fine.

I think a short blurb in the docs with this reasoning would be appreciated. 😃 

Potentially in the Readme just after [Ansible Support](https://github.com/metacloud/molecule#ansible-support) or in the docs under the [Requirements Section](https://molecule.readthedocs.io/en/latest/installation.html#requirements)?

**Comment by retr0h** [comment] 2017-12-28 02:54
Closing.  Molecule will report py3 not supported when running under py3.

**Closed by retr0h** 2017-12-28 02:54 UTC
Labels: question

**Comment by danlamanna** [comment] 2018-03-02 19:29
@retr0h Thanks for going out of your way to try to ensure Py3 compatibility in upstream Ansible, and thanks for molecule!

This information took me a while to find, is there a way to track this information (along with the upstream ansible blockers) in a more obvious location? Maybe the README?

**Comment by lwm** [comment] 2018-06-28 22:45
FYI, https://molecule.readthedocs.io/en/latest/installation.html#requirements says:

> Python 3.6 with Ansible >= 2.4

:rocket: :rocket: :rocket:
